### PR TITLE
Release/2.0.0 and Rename to "repo-automator"

### LINKED ISSUE #73: Rename to Repo Automator?
### Describe your question

Given the scope of this action has expanded beyond just PR automations to other items covering issue automations and project/repo management, it might make sense to update the name (again) to Repo Automator?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### LINKED ISSUE #85: Release version 2.0.0
This issue is for tracking changes for the 2.0.0 release. Target release date: **Aug 2023.**

### Pre-release steps
- [x] Review and merge https://github.com/10up/action-pr-automator/pull/84
- [x] Rename repo to repo automator - https://github.com/10up/action-pr-automator/issues/73

## Release instructions
- [x] Branch: Starting from `develop`, cut a release branch named `release/2.0.0` for your changes.
- [x] Version bump: Bump the version number in `package.json`, `package-lock.json` and any other relevant files if it does not already reflect the version being released.
- [x] Changelog: Add/update the changelog in `CHANGELOG.md`.
- [x] Props: update `CREDITS.md` file with any new contributors, confirm maintainers are accurate.
- [x] New files: Check to be sure any new files/paths that are unnecessary in the production version are included in `.gitattributes`.
- [x] Readme updates: Make any other readme changes as necessary.
- [x] Merge: Make a non-fast-forward merge from your release branch to `develop` (or merge the pull request), then do the same for `develop` into `trunk` (`git checkout trunk && git merge --no-ff develop`). `trunk` contains the stable development version.
- [x] Push: Push your `trunk` branch to GitHub (e.g. `git push origin trunk`).
- [x] Release: Create a [new release](https://github.com/10up/action-pr-automator/releases/new), naming the tag and the release with the new version number, and targeting the `trunk` branch. Paste the changelog from `CHANGELOG.md` into the body of the release and include a link to the closed issues on the [milestone](https://github.com/10up/action-pr-automator/milestone/3?closed=1).
- [x]  Close milestone: Edit the [milestone](https://github.com/10up/action-pr-automator/milestone/3) with release date (in the `Due date (optional)` field) and link to GitHub release (in the `Description` field), then close the milestone.
- [x] Punt incomplete items: If any open issues or PRs which were milestoned for `2.0.0` do not make it into the release, update their milestone to `2.1.0` or `Future Release`.

### Post-release steps
- [ ] Update pr-automator action workflows in "Autoshare for Twitter" and "Publisher media kit" repo.

### PR DESCRIPTION
**Pull request by iamdharmesh**
### Description of the Change
Rename action to "Repo Automator" and version bump to v2.0.0

Closes #73
Closes #85 

### Credits
Props @jeffpaul @iamdharmesh 

### Checklist:

- [x] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests pass.

### CODE REVIEW

**Review by jeffpaul — DISMISSED** [review]
Looks good, but let's hold off on merging this (and renaming the repo) until just before we're ready to merge the next release PR / tag the next release so that these all happen closely together.

**Comment by jeffpaul** [comment]
@iamdharmesh with this change, we might also consider bumping the next version to 2.0.0?

**Comment by iamdharmesh** [comment]
> @iamdharmesh with this change, we might also consider bumping the next version to 2.0.0?

Yes, I agree @jeffpaul. Version 2.0.0 would be more reasonable, considering the renaming and the number of features we have added.

>  let's hold off on merging this (and renaming the repo) until just before we're ready to merge the next release PR / tag the next release so that these all happen closely together.

I will update this PR to bump the version. So, we don't have to review multiple PRs and we can directly ship the release.

**Review by jeffpaul — APPROVED** [review]
Looks good, thanks for handling the release!

**Pull request merged**
