### PR TITLE
Add PR Helper GH Action

### PR DESCRIPTION
**Pull request by iamdharmesh**
### Description of the Change
PR adds PR Helper GH action to help with common PR actions. 

### Changelog Entry

> Added - PR Helper GH Action

### Credits

Props @iamdharmesh

### Checklist:

- [x] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests pass.

### CODE REVIEW

**Comment by jeffpaul** [comment]
Looks good!  What repo do you think we could best test this on next?

**Comment by iamdharmesh** [comment]
I think https://github.com/10up/autoshare-for-twitter will be best, but before that, I want to finalize the request review from the team. for requesting review from the team we need to pass `PAT`, as `GITHUB_TOKEN` don't have permission to request a review from the team, we can request a review from user with `GITHUB_TOKEN` but for requesting a review from the team we have to pass `PAT`.

So, Should we request a review from the team (**10up/open source practice**) or from the repo maintainer? In my opinion, requesting a review from the team is the best option to go with, but for that, I need help from you to set up `PAT` in secrets.

Thanks

**Comment by faisal-alvi** [comment]
I'm ready to test it on SLA and PMK and would like to set myself as a reviewer for both repositories.

**Comment by iamdharmesh** [comment]
Thanks for showing interest in this @faisal-alvi, I raised PR https://github.com/10up/publisher-media-kit/pull/101 to add action and it worked well (Action has requested review from you after matching all PR description requirements).

**Comment by jeffpaul** [comment]
@iamdharmesh can we set up an org PAT to be used for this?  What scopes does it need?

**Comment by iamdharmesh** [comment]
@jeffpaul The PAT needs to have the `repo` scope and the account the PAT belongs to needs to have the write permission to the repository.
> can we set up an org PAT to be used for this?

Not sure about this, we may try to check by using it.

**Comment by jeffpaul** [comment]
@iamdharmesh just DM'd you something to test and see if it works before applying to projects here on GitHub.

**Review by Sidsector9 — APPROVED** [review]

**Pull request merged**
