### PR TITLE
Add support for multiple reviewers

### LINKED ISSUE #44: Add support for multiple reviewers
### Is your enhancement related to a problem? Please describe.

Currently, the action accepts only one reviewer to request a review from. Multiple review should be accepted and review should be requested from all of them. 

### Designs

_No response_

### Describe alternatives you've considered

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by iamdharmesh**
### Description of the Change
Currently, action has support for request review from a single reviewer, This PR adds support for request review from multiple reviewers. 

Closes #44 
### How to test the Change
1. Create a PR Automator workflow
2. Add multiple users/teams in the `reviewers` configuration field. like below:
```
reviewers: |
  iamdharmesh
  ghuser1
  ghuser2
  team:test
```
3. Create a sample PR 
4. Verify review is requested from all reviewers.

### Credits
Props @iamdharmesh.

### Checklist:

- [x] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests pass.

### CODE REVIEW

**Review by faisal-alvi — COMMENTED** [review]
@iamdharmesh thanks for working on this.

1. I've noticed this is working as expected in your example at https://github.com/iamdharmesh/action-pr-validator/pull/46 but when I tried at https://github.com/faisal-alvi/action-pr-automator/pull/1, it failed and said:
`Failed assigned PR to (faisal-alvi) : HttpError: Resource not accessible by integration`

image
[link](https://github.com/faisal-alvi/action-pr-automator/actions/runs/4162575867/jobs/7201913439)

2. Also, even though it failed, the job was successful, I assume the job should be considered failed.

**Comment by iamdharmesh** [comment]
Hi @faisal-alvi, Thanks for checking on this.

> 1. I've noticed this is working as expected in your example at https://github.com/iamdharmesh/action-pr-validator/pull/46 but when I tried at https://github.com/faisal-alvi/action-pr-automator/pull/1, it failed and said:
`Failed assigned PR to (faisal-alvi) : HttpError: Resource not accessible by integration`

It seems this is not related to PR and is something with permissions. can you please check in action settings (`Settings > Actions`) and make sure the workflow has enough permissions?

>2. Also, even though it failed, the job was successful, I assume the job should be considered failed.

As this job is an automation task, it is an optional addition and passed intentionally to don't create confusion at the time of merge PR. The action fails only if the PR description fails the action validation.

Thanks.

**Review by jeffpaul — DISMISSED** [review]
Looks good, thanks!

**Comment by iamdharmesh** [comment]
@faisal-alvi As we discussed, GitHub action only provides read access to `GITHUB_TOKEN` when PR is from the forked repo So, it does not have enough access to assign PR to the author or request a review.

If anyone has a requirement and wants to run the action on PR from forked repo with enough permissions then [`pull_request_target`](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target) event can be used to provide enough permissions when PR is from the forked repo. but it comes with security risks so, needs to use with caution after reading all related information.  More information [here](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target)

Please let me know if you need any further information on this.

Thanks

**Comment by faisal-alvi** [comment]
@iamdharmesh sound good. I think adding these details to the readme could prove helpful for certain users.

**Review by faisal-alvi — DISMISSED** [review]

**Review by faisal-alvi — APPROVED** [review]

**Pull request merged**
